import maplibregl, { CustomLayerInterface, CustomRenderMethodInput, Map } from 'maplibre-gl';
import type { DecodedL3, RadarMetadata } from '../types';
import { destination } from '../geometry';
import { paletteTexture, Palette } from '../palette';
import { fragmentShader, vertexShader } from './shaders';

export type RadarBounds = [number, number, number, number];
export interface RadarCoordinateSample { bearing: number; gate: number; latitude: number; longitude: number; }
export interface RadarDiagnostics {
  decodedValueCount: number; validStateCount: number; minValidDbz: number | null; maxValidDbz: number | null;
  radialCount: number; gateCount: number; boundingBox: RadarBounds | null; intersectsViewport: boolean | null;
  radarCenter: { latitude: number; longitude: number } | null; cardinalSamples: RadarCoordinateSample[]; viewportBounds: RadarBounds | null;
  vertexCount: number; indexCount: number; gpuBufferBytes: number; gpuTextureBytes: number;
  shaderCompile: { vertex: boolean; fragment: boolean }; programLink: boolean; drawCallExecuted: boolean;
  drawCallCount: number; webglErrors: string[];
}

function compile(gl: WebGL2RenderingContext, type: number, source: string, name: string) {
  const shader = gl.createShader(type)!; gl.shaderSource(shader, source); gl.compileShader(shader);
  if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw new Error(`${name} shader compile failed: ${gl.getShaderInfoLog(shader) || 'unknown error'}`);
  return shader;
}
function intersects(a: RadarBounds, b: RadarBounds) { return a[0] <= b[2] && a[2] >= b[0] && a[1] <= b[3] && a[3] >= b[1]; }

export class RadarLayer implements CustomLayerInterface {
  id = 'zasnet-radar'; type = 'custom' as const; renderingMode = '2d' as const;
  private gl?: WebGL2RenderingContext; private map?: Map; private program?: WebGLProgram; private position?: WebGLBuffer; private value?: WebGLBuffer; private state?: WebGLBuffer; private texture?: WebGLTexture;
  private count = 0; private opacity = 0.85; private mode = 2; private visible = true; private debugMagenta = false; private palette: Palette; private decoded?: DecodedL3; private metadata?: RadarMetadata; private geometryKey?: string;
  private diagnostics?: RadarDiagnostics; private onDiagnostic?: (diagnostics: RadarDiagnostics) => void; private lastDiagnosticLog = 0; private drawCallCount = 0; private pendingGlErrors: string[] = [];
  constructor(palette: Palette, onDiagnostic?: (diagnostics: RadarDiagnostics) => void) { this.palette = palette; this.onDiagnostic = onDiagnostic; }
  onAdd(map: Map, gl: WebGLRenderingContext) {
    const webgl = gl as WebGL2RenderingContext;
    if (typeof WebGL2RenderingContext === 'undefined' || !(webgl instanceof WebGL2RenderingContext)) throw new Error('WebGL2 is required');
    this.map = map; this.gl = webgl; this.program = webgl.createProgram()!; let vertexOk = false, fragmentOk = false, linked = false;
    try { const vertex = compile(webgl, webgl.VERTEX_SHADER, vertexShader, 'vertex'); vertexOk = true; const fragment = compile(webgl, webgl.FRAGMENT_SHADER, fragmentShader, 'fragment'); fragmentOk = true; webgl.attachShader(this.program, vertex); webgl.attachShader(this.program, fragment); webgl.linkProgram(this.program); linked = Boolean(webgl.getProgramParameter(this.program, webgl.LINK_STATUS)); if (!linked) throw new Error(`program link failed: ${webgl.getProgramInfoLog(this.program) || 'unknown error'}`); }
    catch (error) { this.recordError(error instanceof Error ? error.message : String(error)); throw error; }
    this.diagnostics = this.emptyDiagnostics(vertexOk, fragmentOk, linked); this.texture = webgl.createTexture()!; this.uploadPalette(); if (this.decoded && this.metadata) { this.logDecodedDiagnostics(); this.uploadGeometry(); } this.publishDiagnostics(true);
  }
  private emptyDiagnostics(vertex = false, fragment = false, linked = false): RadarDiagnostics { return { decodedValueCount: 0, validStateCount: 0, minValidDbz: null, maxValidDbz: null, radialCount: 0, gateCount: 0, boundingBox: null, intersectsViewport: null, radarCenter: null, cardinalSamples: [], viewportBounds: null, vertexCount: 0, indexCount: 0, gpuBufferBytes: 0, gpuTextureBytes: 0, shaderCompile: { vertex, fragment }, programLink: linked, drawCallExecuted: false, drawCallCount: 0, webglErrors: [] }; }
  private recordError(message: string) { this.pendingGlErrors.push(message); }
  private readGlErrors(gl: WebGL2RenderingContext) { for (let error = gl.getError(); error !== gl.NO_ERROR; error = gl.getError()) this.pendingGlErrors.push(`0x${error.toString(16)}`); }
  private publishDiagnostics(force = false) { if (!this.diagnostics) return; this.updateViewport(); this.diagnostics.drawCallCount = this.drawCallCount; this.diagnostics.webglErrors = [...this.pendingGlErrors]; if (force || performance.now() - this.lastDiagnosticLog > 1000) { this.lastDiagnosticLog = performance.now(); console.info('[Radar diagnostics]', this.diagnostics); this.onDiagnostic?.({ ...this.diagnostics, webglErrors: [...this.diagnostics.webglErrors] }); } }
  private updateViewport() { const bounds = this.diagnostics?.boundingBox, mapBounds = this.map?.getBounds(); if (!this.diagnostics || !bounds || !mapBounds) return; const viewport: RadarBounds = [mapBounds.getWest(), mapBounds.getSouth(), mapBounds.getEast(), mapBounds.getNorth()]; this.diagnostics.viewportBounds = viewport; this.diagnostics.intersectsViewport = intersects(bounds, viewport); }
  setData(decoded: DecodedL3, metadata: RadarMetadata) { const key = JSON.stringify([decoded.header.radial_count, decoded.header.gate_count, decoded.header.radials]); const reusable = key === this.geometryKey; this.decoded = decoded; this.metadata = metadata; this.logDecodedDiagnostics(); if (this.gl) reusable ? this.uploadValues() : this.uploadGeometry(); this.geometryKey = key; this.publishDiagnostics(true); }
  private logDecodedDiagnostics() { if (!this.decoded || !this.metadata || !this.diagnostics) return; let valid = 0, min = Infinity, max = -Infinity; for (let i = 0; i < this.decoded.values.length; i++) if (this.decoded.states[i] === 0) { valid++; min = Math.min(min, this.decoded.values[i]); max = Math.max(max, this.decoded.values[i]); } const targetBearings = [0, 90, 180, 270]; const cardinalSamples: RadarCoordinateSample[] = []; for (const bearing of targetBearings) { const radial = this.decoded.header.radials.reduce((best, candidate) => { const distance = Math.abs(((candidate.azimuth - bearing + 540) % 360) - 180); const bestDistance = Math.abs(((best.azimuth - bearing + 540) % 360) - 180); return distance < bestDistance ? candidate : best; }); for (const gate of [0, 1, 2]) { const range = radial.first_gate_m + gate * radial.gate_spacing_m; const [longitude, latitude] = destination(this.metadata.latitude, this.metadata.longitude, bearing, range); cardinalSamples.push({ bearing, gate, latitude, longitude }); } } this.diagnostics.decodedValueCount = this.decoded.values.length; this.diagnostics.validStateCount = valid; this.diagnostics.minValidDbz = valid ? min : null; this.diagnostics.maxValidDbz = valid ? max : null; this.diagnostics.radialCount = this.decoded.header.radial_count; this.diagnostics.gateCount = this.decoded.header.gate_count; this.diagnostics.radarCenter = { latitude: this.metadata.latitude, longitude: this.metadata.longitude }; this.diagnostics.cardinalSamples = cardinalSamples; console.info('[Radar decoded frame]', { radarCenter: this.diagnostics.radarCenter, cardinalSamples, decodedValueCount: this.diagnostics.decodedValueCount, validStateCount: valid, minValidDbz: this.diagnostics.minValidDbz, maxValidDbz: this.diagnostics.maxValidDbz, radialCount: this.diagnostics.radialCount, gateCount: this.diagnostics.gateCount }); }
  getBoundingBox() { return this.diagnostics?.boundingBox ?? null; }
  setPalette(palette: Palette) { this.palette = palette; if (this.gl) this.uploadPalette(); }
  setOpacity(value: number) { this.opacity = value; }
  setVisible(value: boolean) { this.visible = value; }
  setMode(mode: 'Raw' | 'Smooth' | 'Broadcast' | 'Debug Magenta') { this.debugMagenta = mode === 'Debug Magenta'; this.mode = { Raw: 0, Smooth: 1, Broadcast: 2, 'Debug Magenta': 0 }[mode]; }
  private uploadPalette() { const gl = this.gl; if (!gl || !this.texture) return; gl.bindTexture(gl.TEXTURE_2D, this.texture); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 256, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, paletteTexture(this.palette)); if (this.diagnostics) this.diagnostics.gpuTextureBytes = 256 * 4; this.readGlErrors(gl); }
  private uploadGeometry() {
    const gl = this.gl, decoded = this.decoded, metadata = this.metadata; if (!gl || !decoded || !metadata) return; const positions: number[] = [], values: number[] = [], states: number[] = [], projectionSamples: Array<{ longitude: number; latitude: number; mercatorX: number; mercatorY: number }> = []; let minLon = Infinity, minLat = Infinity, maxLon = -Infinity, maxLat = -Infinity;
    for (let r = 0; r < decoded.header.radial_count; r++) for (let g = 0; g < decoded.header.gate_count; g++) { const radial = decoded.header.radials[r], r0 = radial.first_gate_m + g * radial.gate_spacing_m, r1 = r0 + radial.gate_spacing_m; const corners = [[radial.start_azimuth, r0], [radial.end_azimuth, r0], [radial.end_azimuth, r1], [radial.start_azimuth, r1]].map(([bearing, range]) => { const [lon, lat] = destination(metadata.latitude, metadata.longitude, bearing, range); minLon = Math.min(minLon, lon); minLat = Math.min(minLat, lat); maxLon = Math.max(maxLon, lon); maxLat = Math.max(maxLat, lat); const point = maplibregl.MercatorCoordinate.fromLngLat([lon, lat]); if (projectionSamples.length < 8) projectionSamples.push({ longitude: lon, latitude: lat, mercatorX: point.x, mercatorY: point.y }); return [point.x, point.y] as [number, number]; }); const value = decoded.values[r * decoded.header.gate_count + g], state = decoded.states[r * decoded.header.gate_count + g]; for (const i of [0, 1, 2, 0, 2, 3]) { positions.push(...corners[i]); values.push(value); states.push(state); } }
    this.count = values.length; this.position = gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER, this.position); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(positions), gl.STATIC_DRAW); this.value = gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER, this.value); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(values), gl.STATIC_DRAW); this.state = gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER, this.state); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(states), gl.STATIC_DRAW); const gpuBufferBytes = (buffer: WebGLBuffer) => { gl.bindBuffer(gl.ARRAY_BUFFER, buffer); return Number(gl.getBufferParameter(gl.ARRAY_BUFFER, gl.BUFFER_SIZE)); }; if (this.diagnostics) { this.diagnostics.boundingBox = [minLon, minLat, maxLon, maxLat]; this.diagnostics.vertexCount = positions.length / 2; this.diagnostics.indexCount = 0; this.diagnostics.gpuBufferBytes = gpuBufferBytes(this.position) + gpuBufferBytes(this.value) + gpuBufferBytes(this.state); } console.info('[Radar projection]', { radarCenter: { latitude: metadata.latitude, longitude: metadata.longitude }, boundingBox: [minLon, minLat, maxLon, maxLat], mercatorSamples: projectionSamples, transformation: 'geodesic lon/lat -> MercatorCoordinate exactly once' }); this.readGlErrors(gl); this.publishDiagnostics(true);
  }
  private uploadValues() { const gl=this.gl, decoded=this.decoded; if (!gl || !decoded || !this.value || !this.state) return; const values:number[]=[]; const states:number[]=[]; for(let r=0;r<decoded.header.radial_count;r++) for(let g=0;g<decoded.header.gate_count;g++){ const v=decoded.values[r*decoded.header.gate_count+g],s=decoded.states[r*decoded.header.gate_count+g]; for(let i=0;i<6;i++){values.push(v);states.push(s);} } gl.bindBuffer(gl.ARRAY_BUFFER,this.value); gl.bufferSubData(gl.ARRAY_BUFFER,0,new Float32Array(values)); gl.bindBuffer(gl.ARRAY_BUFFER,this.state); gl.bufferSubData(gl.ARRAY_BUFFER,0,new Float32Array(states)); this.readGlErrors(gl); }
  render(gl: WebGLRenderingContext, options: CustomRenderMethodInput) { const g = gl as WebGL2RenderingContext; if (!this.visible || !this.program || !this.position || !this.value || !this.state || !this.texture) return; g.useProgram(this.program); const bind = (buffer: WebGLBuffer, name: string, size: number) => { g.bindBuffer(g.ARRAY_BUFFER, buffer); const location = g.getAttribLocation(this.program!, name); if (location < 0) this.recordError(`missing attribute ${name}`); else { g.enableVertexAttribArray(location); g.vertexAttribPointer(location, size, g.FLOAT, false, 0, 0); } }; bind(this.position, 'a_position', 2); bind(this.value, 'a_value', 1); bind(this.state, 'a_state', 1); g.uniformMatrix4fv(g.getUniformLocation(this.program, 'u_matrix'), false, options.modelViewProjectionMatrix as Float32List); g.uniform1f(g.getUniformLocation(this.program, 'u_opacity'), this.opacity); g.uniform1f(g.getUniformLocation(this.program, 'u_mode'), this.mode); g.uniform1f(g.getUniformLocation(this.program, 'u_debug_magenta'), this.debugMagenta ? 1 : 0); g.activeTexture(g.TEXTURE0); g.bindTexture(g.TEXTURE_2D, this.texture); g.uniform1i(g.getUniformLocation(this.program, 'u_palette'), 0); if (this.debugMagenta) g.disable(g.BLEND); else { g.enable(g.BLEND); g.blendFuncSeparate(g.SRC_ALPHA, g.ONE_MINUS_SRC_ALPHA, g.ONE, g.ONE_MINUS_SRC_ALPHA); } g.drawArrays(g.TRIANGLES, 0, this.count); this.drawCallCount++; if (this.diagnostics) this.diagnostics.drawCallExecuted = true; this.readGlErrors(g); this.publishDiagnostics(); }
  onRemove(map: Map) { const gl = this.gl; if (gl) { for (const buffer of [this.position, this.value, this.state]) if (buffer) gl.deleteBuffer(buffer); if (this.texture) gl.deleteTexture(this.texture); if (this.program) gl.deleteProgram(this.program); } map.triggerRepaint(); }
}
