import { useRef, useState } from 'react';
import type { MapObjectProperties, SceneObject, SceneObjectType } from '../scenes/types';
import type { RadarEditorStatus } from './RadarMapObject';

const labels: Record<SceneObjectType, string> = { map: 'MAP', text: 'TEXT', image: 'IMAGE', shape: 'SHAPE', group: 'GROUP' };

export function PropertiesPanel({ object, radarStatus, onPatch, onMapAction, onImage }: { object?: SceneObject; radarStatus?: RadarEditorStatus; onPatch: (patch: Partial<SceneObject> & { properties?: Record<string, unknown> }) => void; onMapAction: (action: 'fit' | 'reset') => void; onImage: (source: string) => void }) {
  const imageInput = useRef<HTMLInputElement>(null);
  if (!object) return <section className="dock-panel inspector-panel"><div className="dock-title">INTERACTIVE OBJECT</div><div className="inspector-empty">No object selected<br /><small>Select an object in the Previewer or Layers.</small></div></section>;
  const property = (key: string, value: unknown) => onPatch({ properties: { [key]: value } });
  const map = object.type === 'map' ? object.properties as unknown as MapObjectProperties : undefined;
  const center = map?.center || [-108.477, 43.066];
  return <section className="dock-panel inspector-panel"><div className="dock-title"><span>INTERACTIVE OBJECT</span><span className="object-type-tag">{labels[object.type]}</span></div><input className="object-name" value={object.name} aria-label="Object name" onChange={event => onPatch({ name: event.target.value })} />
    <details open><summary>TRANSFORM</summary><div className="field-grid"><Field label="X" value={object.x} onChange={value => onPatch({ x: value })} /><Field label="Y" value={object.y} onChange={value => onPatch({ y: value })} /><Field label="W" value={object.width} onChange={value => onPatch({ width: value })} /><Field label="H" value={object.height} onChange={value => onPatch({ height: value })} /><Field label="Rotation" value={object.rotation} onChange={value => onPatch({ rotation: value })} /></div></details>
    <details open><summary>APPEARANCE</summary><Field label="Opacity" value={object.opacity * 100} suffix="%" onChange={value => onPatch({ opacity: Math.max(0, Math.min(100, value)) / 100 })} /><label className="property-check"><input type="checkbox" checked={object.visible} onChange={event => onPatch({ visible: event.target.checked })} /> Visible</label><label className="property-check"><input type="checkbox" checked={object.locked} onChange={event => onPatch({ locked: event.target.checked })} /> Locked</label></details>
    {object.type === 'map' && <><details open><summary>MAP CAMERA</summary><div className="field-grid"><Field label="Lon" value={center[0]} step=".001" onChange={value => property('center', [value, center[1]])} /><Field label="Lat" value={center[1]} step=".001" onChange={value => property('center', [center[0], value])} /><Field label="Zoom" value={map?.zoom ?? 6} step=".1" onChange={value => property('zoom', value)} /><Field label="Bearing" value={map?.bearing ?? 0} onChange={value => property('bearing', value)} /><Field label="Pitch" value={map?.pitch ?? 0} onChange={value => property('pitch', value)} /></div><div className="inspector-actions"><button onClick={() => onMapAction('fit')}>Fit Radar</button><button onClick={() => onMapAction('reset')}>Reset Camera</button></div></details><details open><summary>RADAR</summary><label className="property-check"><input type="checkbox" checked={map?.radar !== false} onChange={event => property('radar', event.target.checked)} /> Enabled</label><div className="field-grid"><Field label="Opacity" value={(map?.opacity ?? .85) * 100} suffix="%" onChange={value => property('opacity', value / 100)} /><Field label="Loop min" value={map?.loopMinutes ?? 30} onChange={value => property('loopMinutes', value)} /><Field label="Speed" value={map?.playbackSpeed ?? 1} step=".25" onChange={value => property('playbackSpeed', value)} /><Field label="End dwell" value={map?.endDwell ?? 0} onChange={value => property('endDwell', value)} /></div><label>Palette<select value={String(map?.palette || 'ZASNet Broadcast')} onChange={event => property('palette', event.target.value)}>{['ZASNet Broadcast', 'Classic', 'Grayscale Debug'].map(value => <option key={value}>{value}</option>)}</select></label><p className="property-note">{radarStatus?.online ? `LIVE · ${radarStatus.frames} frames` : 'Radar status is shown in the transport bar.'}</p></details><details><summary>MAP LAYERS</summary>{(['states', 'counties', 'roads', 'labels'] as const).map(key => <label className="property-check" key={key}><input type="checkbox" checked={Boolean(map?.[key])} onChange={event => property(key, event.target.checked)} /> {key[0].toUpperCase() + key.slice(1)}</label>)}</details></>}
    {object.type === 'text' && <details open><summary>TEXT / TYPOGRAPHY</summary><label>Content<textarea value={String(object.properties.text || '')} onChange={event => property('text', event.target.value)} /></label><div className="field-grid"><Field label="Size" value={Number(object.properties.fontSize)} onChange={value => property('fontSize', value)} /><Field label="Weight" value={Number(object.properties.fontWeight)} onChange={value => property('fontWeight', value)} /></div><label>Font family<input value={String(object.properties.fontFamily || '')} onChange={event => property('fontFamily', event.target.value)} /></label><label className="property-check"><input type="checkbox" checked={Boolean(object.properties.italic)} onChange={event => property('italic', event.target.checked)} /> Italic</label><label>Alignment<select value={String(object.properties.align || 'left')} onChange={event => property('align', event.target.value)}><option>left</option><option>center</option><option>right</option></select></label><div className="field-grid"><label>Fill<input type="color" value={String(object.properties.color || '#ffffff')} onChange={event => property('color', event.target.value)} /></label><label>Outline<input type="color" value={String(object.properties.outline || '#000000')} onChange={event => property('outline', event.target.value)} /></label></div><Field label="Outline width" value={Number(object.properties.outlineWidth || 0)} onChange={value => property('outlineWidth', value)} /><label className="property-check"><input type="checkbox" checked={Boolean(object.properties.shadow)} onChange={event => property('shadow', event.target.checked)} /> Shadow</label></details>}
    {object.type === 'shape' && <details open><summary>SHAPE</summary><label>Variant<select value={String(object.properties.variant || 'rectangle')} onChange={event => property('variant', event.target.value)}><option>rectangle</option><option>rounded</option><option>ellipse</option></select></label><div className="field-grid"><label>Fill<input type="color" value={String(object.properties.fill || '#26708a')} onChange={event => property('fill', event.target.value)} /></label><label>Stroke<input type="color" value={String(object.properties.border || '#8cc8d8')} onChange={event => property('border', event.target.value)} /></label></div><Field label="Stroke width" value={Number(object.properties.borderWidth || 0)} onChange={value => property('borderWidth', value)} /><Field label="Corner radius" value={Number(object.properties.radius || 0)} onChange={value => property('radius', value)} /></details>}
    {object.type === 'image' && <details open><summary>IMAGE</summary><input ref={imageInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const source = String(reader.result); property('source', source); onImage(source); }; reader.readAsDataURL(file); }} /><button onClick={() => imageInput.current?.click()}>Choose Image…</button><label>Source<input value={String(object.properties.source || '')} onChange={event => property('source', event.target.value)} /></label><label>Fit<select value={String(object.properties.fit || 'contain')} onChange={event => property('fit', event.target.value)}><option>contain</option><option>cover</option><option>fill</option></select></label></details>}
  </section>;
}

function Field({ label, value, suffix, step = '1', onChange }: { label: string; value: number; suffix?: string; step?: string; onChange: (value: number) => void }) { return <label className="number-field">{label}<span><input type="number" step={step} value={Number.isFinite(value) ? Math.round(value * 100) / 100 : 0} onChange={event => onChange(Number(event.target.value))} />{suffix}</span></label>; }

export function LayersPanel({ objects, selectedId, onSelect, onPatch, onReorder, onFront, onBack, onDelete, onContextMenu }: { objects: SceneObject[]; selectedId?: string; onSelect: (id: string) => void; onPatch: (id: string, patch: Partial<SceneObject>) => void; onReorder: (id: string, direction: -1 | 1) => void; onFront: (id: string) => void; onBack: (id: string) => void; onDelete: (id: string) => void; onContextMenu: (event: React.MouseEvent, object: SceneObject) => void }) {
  const ordered = [...objects].sort((a, b) => b.z - a.z); const mapChildren = ['Radar', 'County Borders', 'State Borders', 'Highways', 'City Labels'];
  return <section className="dock-panel layers-panel"><div className="dock-title">LAYERS / OBJECT TREE</div><div className="layers-list">{ordered.map(object => <div key={object.id}><div className={selectedId === object.id ? 'layer-row active' : 'layer-row'}><button className="layer-select" onClick={() => onSelect(object.id)} onContextMenu={event => onContextMenu(event, object)}><span>{object.type === 'map' ? '▧' : object.type === 'text' ? 'T' : object.type === 'shape' ? '◇' : object.type === 'image' ? '▤' : '▱'}</span>{object.name}</button><button title="Visibility" onClick={() => onPatch(object.id, { visible: !object.visible })}>{object.visible ? '◉' : '○'}</button><button title="Lock" onClick={() => onPatch(object.id, { locked: !object.locked })}>{object.locked ? '▣' : '□'}</button><button title="Move up" onClick={() => onReorder(object.id, 1)}>↑</button><button title="Move down" onClick={() => onReorder(object.id, -1)}>↓</button><button title="Bring front" onClick={() => onFront(object.id)}>⇈</button><button title="Send back" onClick={() => onBack(object.id)}>⇊</button><button title="Delete" onClick={() => onDelete(object.id)}>×</button></div>{object.type === 'map' && <div className="layer-children">{mapChildren.map(child => <span key={child}><i />{child}</span>)}</div>}</div>)}</div></section>;
}
