import type { AnimationTrack, Scene, SceneObject } from '../scenes/types';

const label = (property: string) => ({ x: 'Position X', y: 'Position Y', width: 'Width', height: 'Height', rotation: 'Rotation', opacity: 'Opacity', scaleX: 'Scale X', scaleY: 'Scale Y', centerLon: 'Camera Lon', centerLat: 'Camera Lat', zoom: 'Camera Zoom', bearing: 'Camera Bearing', pitch: 'Camera Pitch' }[property] || property);
export function SceneTimeline({ scene, time, playing, autoKey, selectedId, onTime, onDuration, onPlay, onAutoKey, onStart, onEnd, onSelectTrack, onMoveKeyframe, onDeleteKeyframe }: { scene: Scene; time: number; playing: boolean; autoKey: boolean; selectedId?: string; onTime: (time: number) => void; onDuration?: (duration: number) => void; onPlay: () => void; onAutoKey: () => void; onStart: () => void; onEnd: () => void; onSelectTrack: (objectId: string) => void; onMoveKeyframe: (track: AnimationTrack, keyframeId: string, time: number) => void; onDeleteKeyframe: (track: AnimationTrack, keyframeId: string) => void; }) {
  const selectedTracks = scene.animations.filter(track => !selectedId || track.objectId === selectedId);
  const objectName = (id: string) => scene.objects.find(object => object.id === id)?.name || 'Object';
  const percent = (value: number) => `${Math.max(0, Math.min(100, value / Math.max(.01, scene.duration) * 100))}%`;
  return <section className="scene-timeline"><div className="timeline-toolbar"><button onClick={onStart} title="Jump to start">|◀</button><button onClick={onPlay} title={playing ? 'Pause scene' : 'Play scene'}>{playing ? '❚❚' : '▶'}</button><button onClick={onEnd} title="Jump to end">▶|</button><span className="timeline-time">{time.toFixed(2)}s / {scene.duration.toFixed(1)}s</span><label className={autoKey ? 'auto-key active' : 'auto-key'}><input type="checkbox" checked={autoKey} onChange={onAutoKey} /> ◆ Auto-Key</label><label>Duration <input type="number" min=".1" step=".1" value={scene.duration} onChange={event => onDuration?.(Math.max(.1, Number(event.target.value) || scene.duration))} /></label><span className="timeline-end">End: {scene.endBehavior === 'loop' ? 'Loop' : 'Stop'}</span></div><div className="timeline-ruler"><div className="timeline-label">TRACKS</div><div className="timeline-scale" onPointerDown={event => { const rect = event.currentTarget.getBoundingClientRect(); onTime((event.clientX - rect.left) / rect.width * scene.duration); }}>{[0, .25, .5, .75, 1].map(point => <span key={point} style={{ left: `${point * 100}%` }}>{(scene.duration * point).toFixed(point === 0 || point === 1 ? 0 : 1)}s</span>)}<i className="timeline-playhead" style={{ left: percent(time) }} /></div></div><div className="timeline-tracks">{selectedTracks.length ? selectedTracks.map(track => <div className="timeline-track" key={track.id}><button className="timeline-label" onClick={() => onSelectTrack(track.objectId)}>{objectName(track.objectId)}<small>{label(track.property)}</small></button><div className="track-lane">{track.keyframes.map(keyframe => <button key={keyframe.id} className="keyframe" title={`${keyframe.time.toFixed(2)}s · ${keyframe.interpolation}`} style={{ left: percent(keyframe.time) }} onPointerDown={event => { event.stopPropagation(); const rect = event.currentTarget.parentElement!.getBoundingClientRect(); const move = (moveEvent: PointerEvent) => onMoveKeyframe(track, keyframe.id, (moveEvent.clientX - rect.left) / rect.width * scene.duration); const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); }} onContextMenu={event => { event.preventDefault(); onDeleteKeyframe(track, keyframe.id); }}>◆</button>)}<i className="timeline-playhead" style={{ left: percent(time) }} /></div></div>) : <div className="timeline-empty">Select an object and use the ◇ controls in Properties to create animation tracks.</div>}</div></section>;
}
