import { CANVAS_HEIGHT, CANVAS_WIDTH, createScene, createSceneObject, newId, type Scene, type SceneObject, type SceneObjectType } from './types';
import { duplicateTracks } from './animation';
export function createInsertedObject(scene: Scene, type: SceneObjectType, x = 120, y = 120) { const hasMapOrBackground = scene.objects.some(object => object.type === 'map' || object.role === 'background'); if (type === 'map' && !hasMapOrBackground) return { ...createSceneObject('map', 0, 0, CANVAS_WIDTH, CANVAS_HEIGHT, 'Radar Map'), role: 'background' as const, locked: true, z: 0 }; return createSceneObject(type, x, y); }
export function addObject(scene: Scene, type: SceneObjectType) { const object = createInsertedObject(scene, type); return { ...scene, objects: [...scene.objects, object], modifiedAt: new Date().toISOString() }; }
export function updateObject(scene: Scene, id: string, patch: Partial<SceneObject> & { properties?: Record<string, unknown> }) { return { ...scene, objects: scene.objects.map(object => object.id === id ? { ...object, ...patch, properties: patch.properties ? { ...object.properties, ...patch.properties } : object.properties } : object), modifiedAt: new Date().toISOString() }; }
export function updateObjectRespectingLock(scene: Scene, id: string, patch: Partial<SceneObject> & { properties?: Record<string, unknown> }) { const target = scene.objects.find(object => object.id === id); if (!target?.locked) return updateObject(scene, id, patch); const spatial = { ...patch }; delete spatial.x; delete spatial.y; delete spatial.width; delete spatial.height; delete spatial.rotation; return Object.keys(spatial).length ? updateObject(scene, id, spatial) : scene; }
export function removeObject(scene: Scene, id: string) { return { ...scene, objects: scene.objects.filter(object => object.id !== id), modifiedAt: new Date().toISOString() }; }
export function fitObjectToFrame(scene: Scene, id: string) { return updateObject(scene, id, { x: 0, y: 0, width: CANVAS_WIDTH, height: CANVAS_HEIGHT, rotation: 0 }); }
export function setObjectAsBackground(scene: Scene, id: string) { const minimum = Math.min(...scene.objects.map(object => object.z), 0); return updateObject(scene, id, { role: 'background', z: minimum, locked: true }); }
export function reorderObject(scene: Scene, id: string, direction: -1 | 1) { const ordered = [...scene.objects].sort((a, b) => a.z - b.z), index = ordered.findIndex(object => object.id === id), target = index + direction; if (index < 0 || target < 0 || target >= ordered.length) return scene; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; return { ...scene, objects: ordered.map((object, i) => ({ ...object, z: i })), modifiedAt: new Date().toISOString() }; }
export function duplicateScene(scene: Scene): Scene { const now = new Date().toISOString(); const idMap = new Map(scene.objects.map(object => [object.id, newId('object')])); return { ...scene, id: newId('scene'), name: `${scene.name} Copy`, objects: scene.objects.map(object => ({ ...object, id: idMap.get(object.id)! })), animations: scene.objects.flatMap(object => duplicateTracks(scene, object.id, idMap.get(object.id)!)), createdAt: now, modifiedAt: now }; }
export function groupObjects(scene: Scene, ids: string[]) { const selected = scene.objects.filter(object => ids.includes(object.id)); if (selected.length < 2) return scene; const group = createSceneObject('group', Math.min(...selected.map(object => object.x)), Math.min(...selected.map(object => object.y)), Math.max(...selected.map(object => object.x + object.width)) - Math.min(...selected.map(object => object.x)), Math.max(...selected.map(object => object.y + object.height)) - Math.min(...selected.map(object => object.y)), 'Group', { children: ids }); return { ...scene, objects: [...scene.objects, group], modifiedAt: new Date().toISOString() }; }
export function ungroupObject(scene: Scene, id: string) { const group = scene.objects.find(object => object.id === id && object.type === 'group'); return group ? { ...scene, objects: scene.objects.filter(object => object.id !== id), modifiedAt: new Date().toISOString() } : scene; }
export { createScene };
